package evento;
// Generated Apr 28, 2023 8:10:23 AM by Hibernate Tools 4.3.1



/**
 * ContactoId generated by hbm2java
 */
public class ContactoId  implements java.io.Serializable {


     private int codigoPostal;
     private String empresa;

    public ContactoId() {
    }

    public ContactoId(int codigoPostal, String empresa) {
       this.codigoPostal = codigoPostal;
       this.empresa = empresa;
    }
   
    public int getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(int codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ContactoId) ) return false;
		 ContactoId castOther = ( ContactoId ) other; 
         
		 return (this.getCodigoPostal()==castOther.getCodigoPostal())
 && ( (this.getEmpresa()==castOther.getEmpresa()) || ( this.getEmpresa()!=null && castOther.getEmpresa()!=null && this.getEmpresa().equals(castOther.getEmpresa()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodigoPostal();
         result = 37 * result + ( getEmpresa() == null ? 0 : this.getEmpresa().hashCode() );
         return result;
   }   


}


