package evento;
// Generated 30-may-2023 21:57:04 by Hibernate Tools 4.3.1



/**
 * Contacto generated by hbm2java
 */
public class Contacto  implements java.io.Serializable {


     private Integer id;
     private Empresa empresa;
     private String provincia;
     private String calle;
     private int numero;
     private int telefono;

    public Contacto() {
    }

    public Contacto(Empresa empresa, String provincia, String calle, int numero, int telefono) {
       this.empresa = empresa;
       this.provincia = provincia;
       this.calle = calle;
       this.numero = numero;
       this.telefono = telefono;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }




}


