package evento;
// Generated May 30, 2023 1:23:05 PM by Hibernate Tools 4.3.1



/**
 * DireccionId generated by hbm2java
 */
public class DireccionId  implements java.io.Serializable {


     private int id;
     private String usuario;

    public DireccionId() {
    }

    public DireccionId(int id, String usuario) {
       this.id = id;
       this.usuario = usuario;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DireccionId) ) return false;
		 DireccionId castOther = ( DireccionId ) other; 
         
		 return (this.getId()==castOther.getId())
 && ( (this.getUsuario()==castOther.getUsuario()) || ( this.getUsuario()!=null && castOther.getUsuario()!=null && this.getUsuario().equals(castOther.getUsuario()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + ( getUsuario() == null ? 0 : this.getUsuario().hashCode() );
         return result;
   }   


}


