package evento;
// Generated Apr 28, 2023 8:10:23 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private String nombre;
     private String dia;
     private String categoria;
     private String descripcion;
     private int valoracion;
     private Set contactos = new HashSet(0);

    public Empresa() {
    }

	
    public Empresa(String nombre, String dia, String categoria, String descripcion, int valoracion) {
        this.nombre = nombre;
        this.dia = dia;
        this.categoria = categoria;
        this.descripcion = descripcion;
        this.valoracion = valoracion;
    }
    public Empresa(String nombre, String dia, String categoria, String descripcion, int valoracion, Set contactos) {
       this.nombre = nombre;
       this.dia = dia;
       this.categoria = categoria;
       this.descripcion = descripcion;
       this.valoracion = valoracion;
       this.contactos = contactos;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDia() {
        return this.dia;
    }
    
    public void setDia(String dia) {
        this.dia = dia;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getValoracion() {
        return this.valoracion;
    }
    
    public void setValoracion(int valoracion) {
        this.valoracion = valoracion;
    }
    public Set getContactos() {
        return this.contactos;
    }
    
    public void setContactos(Set contactos) {
        this.contactos = contactos;
    }




}


