package evento;
// Generated 30-may-2023 21:57:04 by Hibernate Tools 4.3.1



/**
 * Especializacion generated by hbm2java
 */
public class Especializacion  implements java.io.Serializable {


     private String nombre;
     private Tipo tipo;
     private String catering;
     private String musica;
     private String decoracion;
     private String audiovisuales;
     private String religion;
     private float precio;

    public Especializacion() {
    }

    public Especializacion(String nombre, Tipo tipo, String catering, String musica, String decoracion, String audiovisuales, String religion, float precio) {
       this.nombre = nombre;
       this.tipo = tipo;
       this.catering = catering;
       this.musica = musica;
       this.decoracion = decoracion;
       this.audiovisuales = audiovisuales;
       this.religion = religion;
       this.precio = precio;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    public String getCatering() {
        return this.catering;
    }
    
    public void setCatering(String catering) {
        this.catering = catering;
    }
    public String getMusica() {
        return this.musica;
    }
    
    public void setMusica(String musica) {
        this.musica = musica;
    }
    public String getDecoracion() {
        return this.decoracion;
    }
    
    public void setDecoracion(String decoracion) {
        this.decoracion = decoracion;
    }
    public String getAudiovisuales() {
        return this.audiovisuales;
    }
    
    public void setAudiovisuales(String audiovisuales) {
        this.audiovisuales = audiovisuales;
    }
    public String getReligion() {
        return this.religion;
    }
    
    public void setReligion(String religion) {
        this.religion = religion;
    }
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }




}


