package evento;
// Generated May 30, 2023 1:23:05 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Evento generated by hbm2java
 */
public class Evento  implements java.io.Serializable {


     private Integer id;
     private Lugar lugar;
     private Patrocinador patrocinador;
     private Resenya resenya;
     private Tipo tipo;
     private Usuario usuario;
     private Date fecha;
     private Date horaInicio;
     private Date horaFin;
     private String catering;
     private String musica;
     private String decoracion;
     private String audiovisuales;
     private String religion;
     private float precio;
     private boolean pagado;
     private Set asistentes = new HashSet(0);
     private Set resenyas = new HashSet(0);
     private Set empresas = new HashSet(0);

    public Evento() {
    }

	
    public Evento(Lugar lugar, Patrocinador patrocinador, Resenya resenya, Tipo tipo, Usuario usuario, Date fecha, Date horaInicio, String catering, String musica, String decoracion, String audiovisuales, String religion, float precio, boolean pagado) {
        this.lugar = lugar;
        this.patrocinador = patrocinador;
        this.resenya = resenya;
        this.tipo = tipo;
        this.usuario = usuario;
        this.fecha = fecha;
        this.horaInicio = horaInicio;
        this.catering = catering;
        this.musica = musica;
        this.decoracion = decoracion;
        this.audiovisuales = audiovisuales;
        this.religion = religion;
        this.precio = precio;
        this.pagado = pagado;
    }
    public Evento(Lugar lugar, Patrocinador patrocinador, Resenya resenya, Tipo tipo, Usuario usuario, Date fecha, Date horaInicio, Date horaFin, String catering, String musica, String decoracion, String audiovisuales, String religion, float precio, boolean pagado, Set asistentes, Set resenyas, Set empresas) {
       this.lugar = lugar;
       this.patrocinador = patrocinador;
       this.resenya = resenya;
       this.tipo = tipo;
       this.usuario = usuario;
       this.fecha = fecha;
       this.horaInicio = horaInicio;
       this.horaFin = horaFin;
       this.catering = catering;
       this.musica = musica;
       this.decoracion = decoracion;
       this.audiovisuales = audiovisuales;
       this.religion = religion;
       this.precio = precio;
       this.pagado = pagado;
       this.asistentes = asistentes;
       this.resenyas = resenyas;
       this.empresas = empresas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Lugar getLugar() {
        return this.lugar;
    }
    
    public void setLugar(Lugar lugar) {
        this.lugar = lugar;
    }
    public Patrocinador getPatrocinador() {
        return this.patrocinador;
    }
    
    public void setPatrocinador(Patrocinador patrocinador) {
        this.patrocinador = patrocinador;
    }
    public Resenya getResenya() {
        return this.resenya;
    }
    
    public void setResenya(Resenya resenya) {
        this.resenya = resenya;
    }
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }
    public Date getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }
    public String getCatering() {
        return this.catering;
    }
    
    public void setCatering(String catering) {
        this.catering = catering;
    }
    public String getMusica() {
        return this.musica;
    }
    
    public void setMusica(String musica) {
        this.musica = musica;
    }
    public String getDecoracion() {
        return this.decoracion;
    }
    
    public void setDecoracion(String decoracion) {
        this.decoracion = decoracion;
    }
    public String getAudiovisuales() {
        return this.audiovisuales;
    }
    
    public void setAudiovisuales(String audiovisuales) {
        this.audiovisuales = audiovisuales;
    }
    public String getReligion() {
        return this.religion;
    }
    
    public void setReligion(String religion) {
        this.religion = religion;
    }
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }
    public boolean isPagado() {
        return this.pagado;
    }
    
    public void setPagado(boolean pagado) {
        this.pagado = pagado;
    }
    public Set getAsistentes() {
        return this.asistentes;
    }
    
    public void setAsistentes(Set asistentes) {
        this.asistentes = asistentes;
    }
    public Set getResenyas() {
        return this.resenyas;
    }
    
    public void setResenyas(Set resenyas) {
        this.resenyas = resenyas;
    }
    public Set getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set empresas) {
        this.empresas = empresas;
    }




}


