package evento;
// Generated Apr 28, 2023 8:10:23 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Evento generated by hbm2java
 */
public class Evento  implements java.io.Serializable {


     private Integer id;
     private Reseña reseña;
     private Tipo tipo;
     private Usuario usuario;
     private Date fecha;
     private Date horaInicio;
     private Date horaFin;
     private String catering;
     private String musica;
     private String decoracion;
     private String audiovisuales;
     private String religion;
     private float precio;
     private boolean pagado;
     private String patrocinador;
     private String lugar;
     private Set asistentes = new HashSet(0);

    public Evento() {
    }

	
    public Evento(Reseña reseña, Tipo tipo, Usuario usuario, Date fecha, Date horaInicio, Date horaFin, String religion, float precio, boolean pagado, String patrocinador, String lugar) {
        this.reseña = reseña;
        this.tipo = tipo;
        this.usuario = usuario;
        this.fecha = fecha;
        this.horaInicio = horaInicio;
        this.horaFin = horaFin;
        this.religion = religion;
        this.precio = precio;
        this.pagado = pagado;
        this.patrocinador = patrocinador;
        this.lugar = lugar;
    }
    public Evento(Reseña reseña, Tipo tipo, Usuario usuario, Date fecha, Date horaInicio, Date horaFin, String catering, String musica, String decoracion, String audiovisuales, String religion, float precio, boolean pagado, String patrocinador, String lugar, Set asistentes) {
       this.reseña = reseña;
       this.tipo = tipo;
       this.usuario = usuario;
       this.fecha = fecha;
       this.horaInicio = horaInicio;
       this.horaFin = horaFin;
       this.catering = catering;
       this.musica = musica;
       this.decoracion = decoracion;
       this.audiovisuales = audiovisuales;
       this.religion = religion;
       this.precio = precio;
       this.pagado = pagado;
       this.patrocinador = patrocinador;
       this.lugar = lugar;
       this.asistentes = asistentes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Reseña getReseña() {
        return this.reseña;
    }
    
    public void setReseña(Reseña reseña) {
        this.reseña = reseña;
    }
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }
    public Date getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }
    public String getCatering() {
        return this.catering;
    }
    
    public void setCatering(String catering) {
        this.catering = catering;
    }
    public String getMusica() {
        return this.musica;
    }
    
    public void setMusica(String musica) {
        this.musica = musica;
    }
    public String getDecoracion() {
        return this.decoracion;
    }
    
    public void setDecoracion(String decoracion) {
        this.decoracion = decoracion;
    }
    public String getAudiovisuales() {
        return this.audiovisuales;
    }
    
    public void setAudiovisuales(String audiovisuales) {
        this.audiovisuales = audiovisuales;
    }
    public String getReligion() {
        return this.religion;
    }
    
    public void setReligion(String religion) {
        this.religion = religion;
    }
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }
    public boolean isPagado() {
        return this.pagado;
    }
    
    public void setPagado(boolean pagado) {
        this.pagado = pagado;
    }
    public String getPatrocinador() {
        return this.patrocinador;
    }
    
    public void setPatrocinador(String patrocinador) {
        this.patrocinador = patrocinador;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public Set getAsistentes() {
        return this.asistentes;
    }
    
    public void setAsistentes(Set asistentes) {
        this.asistentes = asistentes;
    }



}


