package evento;
// Generated May 30, 2023 1:23:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Lugar generated by hbm2java
 */
public class Lugar  implements java.io.Serializable {


     private String nombre;
     private String provincia;
     private int codigoPostal;
     private String calle;
     private int numero;
     private int aforo;
     private Set eventos = new HashSet(0);

    public Lugar() {
    }

	
    public Lugar(String nombre, String provincia, int codigoPostal, String calle, int numero, int aforo) {
        this.nombre = nombre;
        this.provincia = provincia;
        this.codigoPostal = codigoPostal;
        this.calle = calle;
        this.numero = numero;
        this.aforo = aforo;
    }
    public Lugar(String nombre, String provincia, int codigoPostal, String calle, int numero, int aforo, Set eventos) {
       this.nombre = nombre;
       this.provincia = provincia;
       this.codigoPostal = codigoPostal;
       this.calle = calle;
       this.numero = numero;
       this.aforo = aforo;
       this.eventos = eventos;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public int getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(int codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public int getAforo() {
        return this.aforo;
    }
    
    public void setAforo(int aforo) {
        this.aforo = aforo;
    }
    public Set getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set eventos) {
        this.eventos = eventos;
    }




}


