package evento;
// Generated Apr 28, 2023 8:10:23 AM by Hibernate Tools 4.3.1



/**
 * Lugar generated by hbm2java
 */
public class Lugar  implements java.io.Serializable {


     private String nombre;
     private String provincia;
     private int codigoPostal;
     private String calle;
     private int numero;
     private int aforo;

    public Lugar() {
    }

    public Lugar(String nombre, String provincia, int codigoPostal, String calle, int numero, int aforo) {
       this.nombre = nombre;
       this.provincia = provincia;
       this.codigoPostal = codigoPostal;
       this.calle = calle;
       this.numero = numero;
       this.aforo = aforo;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public int getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(int codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public int getAforo() {
        return this.aforo;
    }
    
    public void setAforo(int aforo) {
        this.aforo = aforo;
    }




}


