package evento;
// Generated Apr 28, 2023 8:10:23 AM by Hibernate Tools 4.3.1



/**
 * Mensaje generated by hbm2java
 */
public class Mensaje  implements java.io.Serializable {


     private MensajeId id;
     private Usuario usuario;
     private String contenido;

    public Mensaje() {
    }

    public Mensaje(MensajeId id, Usuario usuario, String contenido) {
       this.id = id;
       this.usuario = usuario;
       this.contenido = contenido;
    }
   
    public MensajeId getId() {
        return this.id;
    }
    
    public void setId(MensajeId id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }




}


