package evento;
// Generated May 30, 2023 1:23:05 PM by Hibernate Tools 4.3.1



/**
 * PagoId generated by hbm2java
 */
public class PagoId  implements java.io.Serializable {


     private int tarjetoCredito;
     private String usuario;

    public PagoId() {
    }

    public PagoId(int tarjetoCredito, String usuario) {
       this.tarjetoCredito = tarjetoCredito;
       this.usuario = usuario;
    }
   
    public int getTarjetoCredito() {
        return this.tarjetoCredito;
    }
    
    public void setTarjetoCredito(int tarjetoCredito) {
        this.tarjetoCredito = tarjetoCredito;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PagoId) ) return false;
		 PagoId castOther = ( PagoId ) other; 
         
		 return (this.getTarjetoCredito()==castOther.getTarjetoCredito())
 && ( (this.getUsuario()==castOther.getUsuario()) || ( this.getUsuario()!=null && castOther.getUsuario()!=null && this.getUsuario().equals(castOther.getUsuario()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getTarjetoCredito();
         result = 37 * result + ( getUsuario() == null ? 0 : this.getUsuario().hashCode() );
         return result;
   }   


}


