package evento;
// Generated Apr 28, 2023 8:10:23 AM by Hibernate Tools 4.3.1



/**
 * Patrocinador generated by hbm2java
 */
public class Patrocinador  implements java.io.Serializable {


     private String nombre;
     private Evento evento;
     private String descripcion;
     private int NInvitados;
     private int descuento;
     private int telefono;
     private String email;

    public Patrocinador() {
    }

    public Patrocinador(Evento evento, String descripcion, int NInvitados, int descuento, int telefono, String email) {
       this.evento = evento;
       this.descripcion = descripcion;
       this.NInvitados = NInvitados;
       this.descuento = descuento;
       this.telefono = telefono;
       this.email = email;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Evento getEvento() {
        return this.evento;
    }
    
    public void setEvento(Evento evento) {
        this.evento = evento;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getNInvitados() {
        return this.NInvitados;
    }
    
    public void setNInvitados(int NInvitados) {
        this.NInvitados = NInvitados;
    }
    public int getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(int descuento) {
        this.descuento = descuento;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


