package evento;
// Generated 30-may-2023 21:57:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Resenya generated by hbm2java
 */
public class Resenya  implements java.io.Serializable {


     private Integer id;
     private Evento evento;
     private Usuario usuario;
     private int calificacion;
     private String titulo;
     private String opinion;
     private Set eventos = new HashSet(0);

    public Resenya() {
    }

	
    public Resenya(Evento evento, Usuario usuario, int calificacion, String titulo, String opinion) {
        this.evento = evento;
        this.usuario = usuario;
        this.calificacion = calificacion;
        this.titulo = titulo;
        this.opinion = opinion;
    }
    public Resenya(Evento evento, Usuario usuario, int calificacion, String titulo, String opinion, Set eventos) {
       this.evento = evento;
       this.usuario = usuario;
       this.calificacion = calificacion;
       this.titulo = titulo;
       this.opinion = opinion;
       this.eventos = eventos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Evento getEvento() {
        return this.evento;
    }
    
    public void setEvento(Evento evento) {
        this.evento = evento;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public int getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(int calificacion) {
        this.calificacion = calificacion;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getOpinion() {
        return this.opinion;
    }
    
    public void setOpinion(String opinion) {
        this.opinion = opinion;
    }
    public Set getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set eventos) {
        this.eventos = eventos;
    }




}


