package evento;
// Generated May 30, 2023 1:23:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipo generated by hbm2java
 */
public class Tipo  implements java.io.Serializable {


     private String nombre;
     private Set especializacions = new HashSet(0);
     private Set eventos = new HashSet(0);

    public Tipo() {
    }

	
    public Tipo(String nombre) {
        this.nombre = nombre;
    }
    public Tipo(String nombre, Set especializacions, Set eventos) {
       this.nombre = nombre;
       this.especializacions = especializacions;
       this.eventos = eventos;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getEspecializacions() {
        return this.especializacions;
    }
    
    public void setEspecializacions(Set especializacions) {
        this.especializacions = especializacions;
    }
    public Set getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set eventos) {
        this.eventos = eventos;
    }




}


