package evento;
// Generated 30-may-2023 21:57:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipo generated by hbm2java
 */
public class Tipo  implements java.io.Serializable {


     private String nombre;
     private Evento evento;
     private Set especializacions = new HashSet(0);

    public Tipo() {
    }

	
    public Tipo(Evento evento) {
        this.evento = evento;
    }
    public Tipo(Evento evento, Set especializacions) {
       this.evento = evento;
       this.especializacions = especializacions;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Evento getEvento() {
        return this.evento;
    }
    
    public void setEvento(Evento evento) {
        this.evento = evento;
    }
    public Set getEspecializacions() {
        return this.especializacions;
    }
    
    public void setEspecializacions(Set especializacions) {
        this.especializacions = especializacions;
    }




}


