package evento;
// Generated Apr 30, 2023 1:04:09 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipo generated by hbm2java
 */
public class Tipo  implements java.io.Serializable {


     private String nombre;
     private Set especializacions = new HashSet(0);

    public Tipo() {
    }

	
    public Tipo(String nombre) {
        this.nombre = nombre;
    }
    public Tipo(String nombre, Set especializacions) {
       this.nombre = nombre;
       this.especializacions = especializacions;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getEspecializacions() {
        return this.especializacions;
    }
    
    public void setEspecializacions(Set especializacions) {
        this.especializacions = especializacions;
    }




}


