package evento;
// Generated Apr 28, 2023 8:10:23 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String email;
     private String contraseña;
     private Set mensajes = new HashSet(0);
     private Set eventos = new HashSet(0);
     private Set pagos = new HashSet(0);
     private Set direccions = new HashSet(0);
     private Set reseñas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String email, String contraseña) {
        this.email = email;
        this.contraseña = contraseña;
    }
    public Usuario(String email, String contraseña, Set mensajes, Set eventos, Set pagos, Set direccions, Set reseñas) {
       this.email = email;
       this.contraseña = contraseña;
       this.mensajes = mensajes;
       this.eventos = eventos;
       this.pagos = pagos;
       this.direccions = direccions;
       this.reseñas = reseñas;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getContraseña() {
        return this.contraseña;
    }
    
    public void setContraseña(String contraseña) {
        this.contraseña = contraseña;
    }
    public Set getMensajes() {
        return this.mensajes;
    }
    
    public void setMensajes(Set mensajes) {
        this.mensajes = mensajes;
    }
    public Set getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set eventos) {
        this.eventos = eventos;
    }
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }
    public Set getDireccions() {
        return this.direccions;
    }
    
    public void setDireccions(Set direccions) {
        this.direccions = direccions;
    }
    public Set getReseñas() {
        return this.reseñas;
    }
    
    public void setReseñas(Set reseñas) {
        this.reseñas = reseñas;
    }




}


