package evento;
// Generated May 30, 2023 1:23:05 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String email;
     private String contrasenya;
     private String nombre;
     private String apellidos;
     private Date fechaNac;
     private int telefono;
     private Set mensajes = new HashSet(0);
     private Set resenyas = new HashSet(0);
     private Set eventos = new HashSet(0);
     private Set pagos = new HashSet(0);
     private Set direccions = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String email, String contrasenya, String nombre, String apellidos, Date fechaNac, int telefono) {
        this.email = email;
        this.contrasenya = contrasenya;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.fechaNac = fechaNac;
        this.telefono = telefono;
    }
    public Usuario(String email, String contrasenya, String nombre, String apellidos, Date fechaNac, int telefono, Set mensajes, Set resenyas, Set eventos, Set pagos, Set direccions) {
       this.email = email;
       this.contrasenya = contrasenya;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.fechaNac = fechaNac;
       this.telefono = telefono;
       this.mensajes = mensajes;
       this.resenyas = resenyas;
       this.eventos = eventos;
       this.pagos = pagos;
       this.direccions = direccions;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getContrasenya() {
        return this.contrasenya;
    }
    
    public void setContrasenya(String contrasenya) {
        this.contrasenya = contrasenya;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public Set getMensajes() {
        return this.mensajes;
    }
    
    public void setMensajes(Set mensajes) {
        this.mensajes = mensajes;
    }
    public Set getResenyas() {
        return this.resenyas;
    }
    
    public void setResenyas(Set resenyas) {
        this.resenyas = resenyas;
    }
    public Set getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set eventos) {
        this.eventos = eventos;
    }
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }
    public Set getDireccions() {
        return this.direccions;
    }
    
    public void setDireccions(Set direccions) {
        this.direccions = direccions;
    }




}


